# Generated by Django 4.2.6 on 2023-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51, unique=True)),
                ('slug', models.SlugField(max_length=51, unique=True)),
                ('short_desc', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('project_name', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='portfolios')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('icons', models.CharField(max_length=80)),
                ('desc', models.TextField()),
            ],
        ),
    ]
