# Generated by Django 4.2.6 on 2023-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_team_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
